### PR TITLE
Added macro to compare ntuples

### PR DESCRIPTION
**Pull request by bflaggs**

### CODE REVIEW

**Comment by yipengsun** [comment]
I personally think that is macro should be put inside folder like `macros` or `utils`. @manuelfs @bflaggs What's your opinion on this?

**Comment by bflaggs** [comment]
Additional Requirements:
1. Change tabs from 4 to 2 spaces
2. Rename the function to the name of the file
3. In addition to eventNumber check the runNumber
4. Make the input of the branches a 2D array of strings with type

**Comment by yipengsun** [comment]
@bflaggs I've added a customized `clang-format` template file `.clang-format` in the root directory of this project (in branch `ben`).

To use it, make sure you have `clang` installed, then use the following command **in the root directory of this project**:
```
clang-format -i -style=file utils/crossmatch.C
```

**Comment by yipengsun** [comment]
The next step will be: Make a function that takes a pointer to the root file, and extract all the unique event identifiers:
```cpp
some_return_type some_function(TFile &file) {
  return all_the_unique_event_identifiers;
}
```

After some second thought, the extraction of events should wait until I finish the framework of the second stage.

**Comment by yipengsun** [comment]
Here's my suggestion to the `main` function (pseudo code):

```cpp
int main(argv[*]) {
  TFile small_ntuple;
  TFile large_ntuple;
  
  std::vector event_uids = extract_event_uid(&small_ntuple);
  Something cross_match_result = cross_match(&large_ntuple, &event_uids);
  
  return 0;
}
```

**Comment by yipengsun** [comment]
I think using TFile as output is absolutely fine. As for the comparison, currently you are only manually comparing the `Bplus_P` branch. Can you make the branch name parametric? Also, I think it is a good time to start comparing all branches that have the same variable name.

**Comment by bflaggs** [comment]
The most recent macro added does the following.

1. Extracts both the unique and duplicate IDs and saves them to separate .root files.

2. Saves the eventNumber and runNumber for each of the separate files into two different vectors, one for unique IDs and one for duplicate IDs.

3. Crossmatches Manuel and Phoebe's ntuples, although I do this using the TFiles themselves (the .root files) not the separate vectors.

**Comment by yipengsun** [comment]
Don't worry about looping over all branches in a tree. I'll take care of that with my infrastructure.

**Comment by yipengsun** [comment]
I've manually merged `ben` to `master`. Closed for now.

**Pull request closed without merging**
